import type { Metadata } from "next";
import React, { JSX } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en" className="md:overflow-hidden">
      <body className="md:overflow-hidden">
        {children}
      </body>
    </html>
  );
}
